# Use container based infra
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
virtualenv:
  # We have to use the distro packaged python-dbus instead of installing
  # from PyPi because travis runs on 14.04 which has DBus 1.6 but the
  # latest python-dbus packaged on PyPi requires 1.8+ to build.
  system_site_packages: true

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - dbus
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - python-dbus
      - python3-dbus

before_install:
  - env
  - echo "Python diagnostic Information"
  - pyenv --version
  - pyenv versions
  - pyenv global
  - 'which -a python'
  - python --version
  - python-config --includes
  - python-config --libs
  - python-config --ldflags
  - pip --version
  - ls -l ~/virtualenv

install:
  - pip install ".[test, docs]" -e .

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    # The dbus-python maintainer hit these bugs on travis, see his comments on the
    # travis bug report: https://github.com/travis-ci/travis-ci/issues/6530
    # See https://github.com/mitya57/secretstorage/blob/2636a47b45aff51a21dfaf1cbd9f1f3c1347f7f4/.travis.yml for an example workaround
    # This is also a known issue and filed on the python bugtracker: https://bugs.python.org/issue7352
    - 'PYTHON_LIBS="-L$(python-config --prefix)/lib $(python-config --libs)"'
    - PY_ENABLE_SHARD=0
